#!/bin/bash

source vars

if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    exit
fi


echo $1
cd "$1"

PREFIXDIR=$(readlink -f ~/.local/share/wineprefixes/$PREFIX)

if [ -d "$PREFIXDIR" ]; then
  echo "Prefix already exists"
else
  echo "Prefix does not exist, creating..."
  winetricks prefix=$PREFIX d3dcompiler_43 corefonts
fi

mv libGLESv2.dll libGLESv2.dll.BAK
WINEPREFIX=~/.local/share/wineprefixes/$PREFIX wine Game.exe
mv libGLESv2.dll.BAK libGLESv2.dll
