#!/bin/bash

source vars

if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    exit
fi


echo $1
cd "$1"

WINEPREFIX=~/.local/share/wineprefixes/$PREFIX LANG="ja_JP.UTF8" wine Game.exe
